FROM python:3.11

# Set working directory
WORKDIR /app

# Install vim and remove cache
# RUN apt-get update && apt-get install -y vim && rm -rf /var/lib/apt/lists/*

# Install Python libraries
RUN pip install numpy pandas matplotlib

# Start bash shell
CMD ["bash"]
